import { getSynthesizeSpeechUrl } from '@aws-sdk/polly-request-presigner';
import { DescribeVoicesCommand, PollyClient, SynthesizeSpeechInput, Voice, VoiceId } from '@aws-sdk/client-polly';
import { fromCognitoIdentityPool } from '@aws-sdk/credential-providers';
import { XhrHttpHandler } from "@aws-sdk/xhr-http-handler";

import { AmazonPollyData } from "../state/config/config.feature";
import { Logger } from "@smithy/types";

/**
 * Service for Amazon Polly Text-to-Speech integration.
 *
 * This service provides functionality to generate presigned URLs for synthesized speech
 * using Amazon Polly. It handles AWS Cognito authentication and configures the Polly client
 * with the provided credentials and region settings.
 *
 * Amazon Polly is a pay-as-you-use TTS service with competitive pricing and fast response times.
 */
export class AwsTtsService {
    private readonly logger: Logger;
    private readonly pollyConfig: AmazonPollyData;
    private _voices: Voice[] | undefined;

    public constructor(pollyConfig: AmazonPollyData, logger: Logger) {
        if (!pollyConfig.poolId) {
            throw new Error(`Oops! You didn't provide a Pool ID for Amazon Polly.`);
        }

        this.pollyConfig = pollyConfig;
        this.logger = logger;
    }

    private async getCredentials() {
        const credentials = await fromCognitoIdentityPool({
            logger: this.logger,
            clientConfig: {
                region: this.pollyConfig.region,
                logger: this.logger,
                userAgentAppId: "TTS Helper",
                requestHandler: new XhrHttpHandler(),
            },
            identityPoolId: this.pollyConfig.poolId.trim(),
        })();
        this.logger.debug(`Retrieved AWS credentials for identity: ${credentials.identityId}`, 'AwsTtsService');
        return credentials;
    }

    private async getClient(): Promise<PollyClient> {
        this.logger.debug(`Creating PollyClient.`, 'AwsTtsService');
        return new PollyClient({
            region: this.pollyConfig.region,
            credentials: await this.getCredentials(),
            logger: this.logger,
            requestHandler: new XhrHttpHandler(),
        });
    }

    /**
     * All voices supported by Amazon Polly, for all languages, and all engines.
     */
    public static get allVoices() {
        return Object.values(VoiceId) as string[];
    }

    /**
     * Voices available for synthesis by Amazon Polly, for US English.
     */
    public async getAvailableVoices() {
        if(!this._voices) {
            const pollyClient = await this.getClient();
            const command = new DescribeVoicesCommand({
                LanguageCode: "en-US",
                IncludeAdditionalLanguageCodes: false,
            });
            const response = await pollyClient.send(command);
            this._voices = response.Voices!;
            this.logger.debug(`Retrieved ${this._voices.length} voices from Polly.`, 'AwsTtsService');
        }
        return this._voices;
    }

    /**
     * Creates a signed URL for an audio file generated by Amazon Polly.
     *
     * @param audioText - The text to be synthesized into audio.
     * @param voice - The voice to use for synthesis. Must be one of `AwsTtsService.availableVoices`.
     * @returns A Promise that resolves to the signed URL for the generated audio file.
     * @throws RangeError if the provided voice is not supported.
     */
    public async getFileURI(audioText: string, voice: string | VoiceId) {
        if (!AwsTtsService.allVoices.includes(voice)) {
            throw new RangeError('Invalid voice. Must be one of `AwsTtsService.availableVoices`');
        }

        const pollyParams = {
            OutputFormat: 'mp3',
            SampleRate: '22050',
            Text: audioText,
            TextType: 'text',
            VoiceId: voice as VoiceId,
        } satisfies SynthesizeSpeechInput;
        this.logger.debug(`pollyParams:\n${JSON.stringify(pollyParams)}`, 'AwsTtsService');

        const pollyClient = await this.getClient();
        const url = await getSynthesizeSpeechUrl({
            client: pollyClient,
            params: pollyParams,
        });
        this.logger.debug(`TTS URI: ${url}`, 'AwsTtsService');
        return url.toString();
    }
}
